[2025-03-08T20:09:28.197+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T20:09:28.228+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.load_to_gold_layer manual__2025-03-08T12:43:13.309365+00:00 [queued]>
[2025-03-08T20:09:28.246+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.load_to_gold_layer manual__2025-03-08T12:43:13.309365+00:00 [queued]>
[2025-03-08T20:09:28.247+0000] {taskinstance.py:2865} INFO - Starting attempt 15 of 16
[2025-03-08T20:09:28.281+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_gold_layer> on 2025-03-08 12:43:13.309365+00:00
[2025-03-08T20:09:28.292+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-08T20:09:28.300+0000] {standard_task_runner.py:72} INFO - Started process 5122 to run task
[2025-03-08T20:09:28.307+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'load_to_gold_layer', 'manual__2025-03-08T12:43:13.309365+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmpe2nz5ay4']
[2025-03-08T20:09:28.308+0000] {standard_task_runner.py:105} INFO - Job 430: Subtask load_to_gold_layer
[2025-03-08T20:09:28.466+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.load_to_gold_layer manual__2025-03-08T12:43:13.309365+00:00 [running]> on host 70b3b9cfbba0
[2025-03-08T20:09:28.633+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='load_to_gold_layer' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T12:43:13.309365+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T12:43:13.309365+00:00'
[2025-03-08T20:09:28.636+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-08T20:09:28.674+0000] {logging_mixin.py:190} INFO - Execution Date: 2025-03-08
[2025-03-08T20:09:28.686+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-08T20:09:28.725+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-08T20:09:31.265+0000] {logging_mixin.py:190} INFO -    column00  ...                                          pgn_trans
0         0  ...  1. e4 c6 2. d4 e5 3. Bc4 d5 4. exd5 cxd5 5. Bb...
1         1  ...  1. d4 e5 2. c4 exd4 3. Qxd4 c5 4. Qd1 Nc6 5. N...
2         2  ...  1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. Ng5 h6 5. Nx...
3         3  ...  1. d4 e5 2. dxe5 Bc5 3. Nc3 Nc6 4. Nf3 Nge7 5....
4         4  ...  1. e4 c5 2. Nf3 d6 3. Bc4 Nd7 4. Ng5 e6 5. Qf3...

[5 rows x 24 columns]
[2025-03-08T20:09:31.280+0000] {logging_mixin.py:190} INFO - [(0, 'https://www.chess.com/game/live/123421379368', '120+1', True, 'bullet', 'chess', 927, 'resigned', 928, 'win', 'Live Chess', 'Chess.com', datetime.date(2025, 3, 1), 'Rhythmbear1', 'sa2_3', '0-1', 'r1b5/pp6/2n5/3k2b1/3qp3/8/PPP3PP/5R1K w - -', 'UTC', 'C23', 'https://www.chess.com/openings/Bishops-Opening-Philidor-Counterattack-3.d4-d5-4.exd5-cxd5', datetime.time(11, 59, 7), datetime.time(12, 2, 25), 'e4 c6 d4 e5 Bc4 d5 exd5 cxd5 Bb3 e4 f3 exf3 Nxf3 Nf6 O-O Be7 Re1 O-O Bg5 Ne4 Ne5 Bxg5 Nxf7 Rxf7 Rxe4 dxe4 Bxf7+ Kxf7 Qh5+ g6 Qxh7+ Kf6 Nd2 Qxd4+ Kh1 Bxd2 Rf1+ Ke5 Qxg6 Nc6 Qf6+ Kd5 Qg5+ Bxg5', '1. e4 c6 2. d4 e5 3. Bc4 d5 4. exd5 cxd5 5. Bb3 e4 6. f3 exf3 7. Nxf3 Nf6 8. O-O Be7 9. Re1 O-O 10. Bg5 Ne4 11. Ne5 Bxg5 12. Nxf7 Rxf7 13. Rxe4 dxe4 14. Bxf7+ Kxf7 15. Qh5+ g6 16. Qxh7+ Kf6 17. Nd2 Qxd4+ 18. Kh1 Bxd2 19. Rf1+ Ke5 20. Qxg6 Nc6 21. Qf6+ Kd5 22. Qg5+ Bxg5', 2014), (1, 'https://www.chess.com/game/live/123421480904', '120+1', True, 'bullet', 'chess', 986, 'win', 920, 'timeout', 'Live Chess', 'Chess.com', datetime.date(2025, 3, 1), 'SoulEaterEXO9', 'Rhythmbear1', '1-0', 'r4rk1/5pp1/7p/3p4/P7/4P3/1Q1p1PPP/2R2RK1 b - -', 'UTC', 'A40', 'https://www.chess.com/openings/Englund-Gambit', datetime.time(12, 2, 46), datetime.time(12, 6, 44), 'd4 e5 c4 exd4 Qxd4 c5 Qd1 Nc6 Nf3 Nf6 Nc3 Be7 Bg5 O-O e3 h6 Bh4 a6 Bd3 b5 cxb5 axb5 Nxb5 Qa5+ Nc3 Nd5 O-O Nxc3 bxc3 Bxh4 Nxh4 Qxc3 Nf5 d5 Qg4 Bxf5 Bxf5 Ne5 Qf4 c4 a4 Nd3 Bxd3 cxd3 Rac1 Qb2 Qd4 d2 Qxb2', '1. d4 e5 2. c4 exd4 3. Qxd4 c5 4. Qd1 Nc6 5. Nf3 Nf6 6. Nc3 Be7 7. Bg5 O-O 8. e3 h6 9. Bh4 a6 10. Bd3 b5 11. cxb5 axb5 12. Nxb5 Qa5+ 13. Nc3 Nd5 14. O-O Nxc3 15. bxc3 Bxh4 16. Nxh4 Qxc3 17. Nf5 d5 18. Qg4 Bxf5 19. Bxf5 Ne5 20. Qf4 c4 21. a4 Nd3 22. Bxd3 cxd3 23. Rac1 Qb2 24. Qd4 d2 25. Qxb2 ', 2014), (2, 'https://www.chess.com/game/live/123421594752', '120+1', True, 'bullet', 'chess', 912, 'resigned', 919, 'win', 'Live Chess', 'Chess.com', datetime.date(2025, 3, 1), 'Rhythmbear1', 'Valentin_formica', '0-1', 'r5k1/ppp3p1/5n1p/4b3/6b1/3P4/P1P3PP/RN5K w - -', 'UTC', 'C57', 'https://www.chess.com/openings/Italian-Game-Knight-Attack', datetime.time(12, 6, 52), datetime.time(12, 9, 1), 'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 h6 Nxf7 Qe7 Nxh8 Nxe4 Ng6 Qf6 O-O Qxg6 f4 d6 fxe5 dxe5 Bf7+ Qxf7 Rxf7 Kxf7 Qh5+ Kg8 d3 Nf6 Qf3 Bg4 Qg3 Bc5+ Be3 Nd4 Bxd4 Bxd4+ Kh1 Bxb2 Qxe5 Bxe5', '1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. Ng5 h6 5. Nxf7 Qe7 6. Nxh8 Nxe4 7. Ng6 Qf6 8. O-O Qxg6 9. f4 d6 10. fxe5 dxe5 11. Bf7+ Qxf7 12. Rxf7 Kxf7 13. Qh5+ Kg8 14. d3 Nf6 15. Qf3 Bg4 16. Qg3 Bc5+ 17. Be3 Nd4 18. Bxd4 Bxd4+ 19. Kh1 Bxb2 20. Qxe5 Bxe5', 2014), (3, 'https://www.chess.com/game/live/123421658130', '120+1', True, 'bullet', 'chess', 899, 'resigned', 920, 'win', 'Live Chess', 'Chess.com', datetime.date(2025, 3, 1), 'Smartservos', 'Rhythmbear1', '0-1', 'r1b3k1/p2p2pp/1ppBrp2/8/1P2P2n/8/qPQ2PPP/3R1RK1 w - -', 'UTC', 'A40', 'https://www.chess.com/openings/Englund-Gambit-2.dxe5-Bc5', datetime.time(12, 9, 7), datetime.time(12, 12, 10), 'd4 e5 dxe5 Bc5 Nc3 Nc6 Nf3 Nge7 e4 Ng6 Bd3 Ncxe5 O-O Nxd3 Qxd3 O-O Bg5 f6 Be3 Bd6 Rad1 Qe7 Nd5 Qf7 c3 c6 Nb4 Bxb4 cxb4 Qxa2 Bc5 Re8 Qc2 b6 Bd6 Re6 Nh4 Nxh4', '1. d4 e5 2. dxe5 Bc5 3. Nc3 Nc6 4. Nf3 Nge7 5. e4 Ng6 6. Bd3 Ncxe5 7. O-O Nxd3 8. Qxd3 O-O 9. Bg5 f6 10. Be3 Bd6 11. Rad1 Qe7 12. Nd5 Qf7 13. c3 c6 14. Nb4 Bxb4 15. cxb4 Qxa2 16. Bc5 Re8 17. Qc2 b6 18. Bd6 Re6 19. Nh4 Nxh4', 2014), (4, 'https://www.chess.com/game/live/123421749462', '120+1', True, 'bullet', 'chess', 913, 'timeout', 962, 'win', 'Live Chess', 'Chess.com', datetime.date(2025, 3, 1), 'Rhythmbear1', 'mishahhd', '0-1', '8/5pbk/7p/q2p4/2pP4/2Pb2NP/3Q1PPK/8 w - -', 'UTC', 'B50', 'https://www.chess.com/openings/Sicilian-Defense-2.Nf3-d6-3.Bc4', datetime.time(12, 12, 20), datetime.time(12, 17, 50), 'e4 c5 Nf3 d6 Bc4 Nd7 Ng5 e6 Qf3 Ngf6 O-O Be7 d3 O-O b3 h6 Nh3 a6 a4 b6 Na3 Bb7 Bb2 Qc7 Bxf6 Bxf6 Rab1 Ne5 Qe2 Nxc4 Nxc4 b5 axb5 axb5 Ne3 Rad8 Nf4 d5 Nh5 Bd4 exd5 exd5 Nf5 Rfe8 Nxh6+ Kh7 Qg4 gxh6 Ng3 Bc8 Qd1 Bf5 Qh5 Bg6 Qd1 Re7 Qd2 Rde8 c3 Bg7 d4 c4 bxc4 bxc4 Rfe1 Rxe1+ Rxe1 Rxe1+ Qxe1 Bd3 Qd2 Qa5 h3 Qa1+ Kh2 Qa5', '1. e4 c5 2. Nf3 d6 3. Bc4 Nd7 4. Ng5 e6 5. Qf3 Ngf6 6. O-O Be7 7. d3 O-O 8. b3 h6 9. Nh3 a6 10. a4 b6 11. Na3 Bb7 12. Bb2 Qc7 13. Bxf6 Bxf6 14. Rab1 Ne5 15. Qe2 Nxc4 16. Nxc4 b5 17. axb5 axb5 18. Ne3 Rad8 19. Nf4 d5 20. Nh5 Bd4 21. exd5 exd5 22. Nf5 Rfe8 23. Nxh6+ Kh7 24. Qg4 gxh6 25. Ng3 Bc8 26. Qd1 Bf5 27. Qh5 Bg6 28. Qd1 Re7 29. Qd2 Rde8 30. c3 Bg7 31. d4 c4 32. bxc4 bxc4 33. Rfe1 Rxe1+ 34. Rxe1 Rxe1+ 35. Qxe1 Bd3 36. Qd2 Qa5 37. h3 Qa1+ 38. Kh2 Qa5', 2014)]
[2025-03-08T20:09:31.849+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python_scripts.py", line 189, in load_to_gold_layer
    """).fetchdf()
        ^^^^^^^^^
duckdb.duckdb.NotImplementedException: Not implemented Error: Unsupported type "TIME WITH TIME ZONE"
[2025-03-08T20:09:31.869+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pull_data_from_chess_api, task_id=load_to_gold_layer, run_id=manual__2025-03-08T12:43:13.309365+00:00, execution_date=20250308T124313, start_date=20250308T200928, end_date=20250308T200931
[2025-03-08T20:09:31.893+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-08T20:09:31.894+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 430 for task load_to_gold_layer (Not implemented Error: Unsupported type "TIME WITH TIME ZONE"; 5122)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python_scripts.py", line 189, in load_to_gold_layer
    """).fetchdf()
        ^^^^^^^^^
duckdb.duckdb.NotImplementedException: Not implemented Error: Unsupported type "TIME WITH TIME ZONE"
[2025-03-08T20:09:31.937+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-08T20:09:31.967+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T20:09:31.970+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
