[2025-02-18T16:10:55.174+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:10:55.212+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-02-18T16:10:55.233+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-02-18T16:10:55.233+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:10:55.274+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2023-10-01 00:00:00+00:00
[2025-02-18T16:10:55.291+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3012) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:10:55.301+0000] {standard_task_runner.py:72} INFO - Started process 3013 to run task
[2025-02-18T16:10:55.304+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpi57y3b7r']
[2025-02-18T16:10:55.308+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask extract_data_from_chess_api
[2025-02-18T16:10:55.483+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:10:55.837+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2025-02-18T16:10:55.839+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:10:56.728+0000] {logging_mixin.py:190} INFO - Successfully Fetche Data From CHess.com API, Records Pulled: 141
[2025-02-18T16:10:56.731+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-02-18T16:10:56.783+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:10:56.825+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:10:59.041+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage
[2025-02-18T16:10:59.046+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-02-18T16:10:59.173+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:10:59.176+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2023-10-01T00:00:00+00:00, execution_date=20231001T000000, start_date=20250218T161055, end_date=20250218T161059
[2025-02-18T16:10:59.313+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:10:59.438+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:10:59.446+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T16:40:39.119+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:40:39.164+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-02-18T16:40:39.183+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-02-18T16:40:39.184+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:40:39.220+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2023-10-01 00:00:00+00:00
[2025-02-18T16:40:39.235+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3734) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:40:39.239+0000] {standard_task_runner.py:72} INFO - Started process 3735 to run task
[2025-02-18T16:40:39.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpe7a220_z']
[2025-02-18T16:40:39.244+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask extract_data_from_chess_api
[2025-02-18T16:40:39.359+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:40:39.562+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2025-02-18T16:40:39.564+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:40:39.570+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2023 and Month: 10, formatted as 10
[2025-02-18T16:40:39.571+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2023/10
[2025-02-18T16:40:40.462+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 141
[2025-02-18T16:40:40.464+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-02-18T16:40:40.521+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:40:40.563+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:40:42.886+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as raw/2023-10-games.json
[2025-02-18T16:40:42.888+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-02-18T16:40:42.930+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:40:42.931+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2023-10-01T00:00:00+00:00, execution_date=20231001T000000, start_date=20250218T164039, end_date=20250218T164042
[2025-02-18T16:40:42.964+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:40:43.005+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:40:43.012+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-10T01:35:18.946+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T01:35:18.973+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-03-10T01:35:18.990+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-03-10T01:35:18.991+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-10T01:35:19.014+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2023-10-01 00:00:00+00:00
[2025-03-10T01:35:19.023+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=16894) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T01:35:19.026+0000] {standard_task_runner.py:72} INFO - Started process 16896 to run task
[2025-03-10T01:35:19.026+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '514', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmpw7owjruc']
[2025-03-10T01:35:19.030+0000] {standard_task_runner.py:105} INFO - Job 514: Subtask extract_data_from_chess_api
[2025-03-10T01:35:19.095+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2023-10-01T00:00:00+00:00 [running]> on host 70b3b9cfbba0
[2025-03-10T01:35:19.198+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2025-03-10T01:35:19.199+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T01:35:19.202+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2023 and Month: 10, formatted as 10
[2025-03-10T01:35:19.203+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2023/10
[2025-03-10T01:35:20.321+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 141
[2025-03-10T01:35:20.323+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-03-10T01:35:20.349+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-10T01:35:20.360+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-10T01:35:22.023+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as bronze/2023-10-games.json
[2025-03-10T01:35:22.024+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-10T01:35:22.050+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T01:35:22.050+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2023-10-01T00:00:00+00:00, execution_date=20231001T000000, start_date=20250310T013518, end_date=20250310T013522
[2025-03-10T01:35:22.095+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T01:35:22.127+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T01:35:22.130+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
