[2025-02-18T16:44:07.041+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:44:07.094+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-08-01T00:00:00+00:00 [queued]>
[2025-02-18T16:44:07.117+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-08-01T00:00:00+00:00 [queued]>
[2025-02-18T16:44:07.119+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:44:07.164+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2024-08-01 00:00:00+00:00
[2025-02-18T16:44:07.184+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3909) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:44:07.189+0000] {standard_task_runner.py:72} INFO - Started process 3910 to run task
[2025-02-18T16:44:07.205+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2024-08-01T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp44ccfgtn']
[2025-02-18T16:44:07.208+0000] {standard_task_runner.py:105} INFO - Job 229: Subtask extract_data_from_chess_api
[2025-02-18T16:44:07.385+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-08-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:44:07.635+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-01T00:00:00+00:00'
[2025-02-18T16:44:07.638+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:44:07.644+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2024 and Month: 8, formatted as 08
[2025-02-18T16:44:07.645+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2024/08
[2025-02-18T16:44:09.474+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 309
[2025-02-18T16:44:09.476+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-02-18T16:44:09.557+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:44:09.589+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:44:12.372+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as raw/2024-08-games.json
[2025-02-18T16:44:12.376+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-02-18T16:44:12.423+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:44:12.423+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2024-08-01T00:00:00+00:00, execution_date=20240801T000000, start_date=20250218T164407, end_date=20250218T164412
[2025-02-18T16:44:12.466+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:44:12.518+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:44:12.521+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-10T01:39:10.205+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T01:39:10.222+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-08-01T00:00:00+00:00 [queued]>
[2025-03-10T01:39:10.230+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-08-01T00:00:00+00:00 [queued]>
[2025-03-10T01:39:10.230+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-10T01:39:10.243+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2024-08-01 00:00:00+00:00
[2025-03-10T01:39:10.250+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=17445) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T01:39:10.252+0000] {standard_task_runner.py:72} INFO - Started process 17447 to run task
[2025-03-10T01:39:10.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2024-08-01T00:00:00+00:00', '--job-id', '544', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmpbkkb60ry']
[2025-03-10T01:39:10.255+0000] {standard_task_runner.py:105} INFO - Job 544: Subtask extract_data_from_chess_api
[2025-03-10T01:39:10.301+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-08-01T00:00:00+00:00 [running]> on host 70b3b9cfbba0
[2025-03-10T01:39:10.391+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-01T00:00:00+00:00'
[2025-03-10T01:39:10.392+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T01:39:10.394+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2024 and Month: 8, formatted as 08
[2025-03-10T01:39:10.395+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2024/08
[2025-03-10T01:39:11.884+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 309
[2025-03-10T01:39:11.885+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-03-10T01:39:11.917+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-10T01:39:11.927+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-10T01:39:14.234+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as bronze/2024-08-games.json
[2025-03-10T01:39:14.235+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-10T01:39:14.260+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T01:39:14.261+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2024-08-01T00:00:00+00:00, execution_date=20240801T000000, start_date=20250310T013910, end_date=20250310T013914
[2025-03-10T01:39:14.291+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T01:39:14.320+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T01:39:14.322+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
