[2025-03-26T01:59:20.351+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T01:59:20.401+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_warehouse.create_data_warehouse manual__2025-03-12T14:13:58.419334+00:00 [queued]>
[2025-03-26T01:59:20.427+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_warehouse.create_data_warehouse manual__2025-03-12T14:13:58.419334+00:00 [queued]>
[2025-03-26T01:59:20.428+0000] {taskinstance.py:2865} INFO - Starting attempt 8 of 9
[2025-03-26T01:59:20.463+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): create_data_warehouse> on 2025-03-12 14:13:58.419334+00:00
[2025-03-26T01:59:20.480+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=29579) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T01:59:20.484+0000] {standard_task_runner.py:72} INFO - Started process 29588 to run task
[2025-03-26T01:59:20.485+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_data_warehouse', 'create_data_warehouse', 'manual__2025-03-12T14:13:58.419334+00:00', '--job-id', '755', '--raw', '--subdir', 'DAGS_FOLDER/load_data_warehouse_dag.py', '--cfg-path', '/tmp/tmpziu0v8qu']
[2025-03-26T01:59:20.491+0000] {standard_task_runner.py:105} INFO - Job 755: Subtask create_data_warehouse
[2025-03-26T01:59:20.689+0000] {task_command.py:467} INFO - Running <TaskInstance: load_data_warehouse.create_data_warehouse manual__2025-03-12T14:13:58.419334+00:00 [running]> on host 8de4e0a4beb2
[2025-03-26T01:59:20.939+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_warehouse' AIRFLOW_CTX_TASK_ID='create_data_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T14:13:58.419334+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T14:13:58.419334+00:00'
[2025-03-26T01:59:20.941+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-26T01:59:20.944+0000] {sql.py:266} INFO - Executing: -- Fact Tables Creating
CREATE SCHEMA IF NOT EXISTS chess_dw;
CREATE TABLE IF NOT EXISTS chess_dw.fact_games (
    game_url VARCHAR PRIMARY KEY,
    time_control VARCHAR,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    game_duration_secs INTEGER,
    time_control VARCHAR,
    my_color VARCHAR,
    my_rating INTEGER,
    opponent_rating INTEGER,
    my_result VARCHAR,
    opponent_result VARCHAR,
    game_fen VARCHAR,
    opening_url VARCHAR,
    game_pgn VARCHAR
);


-- Dimension tables creation
CREATE TABLE IF NOT EXISTS chess_dw.dim_date (
    date_id INTEGER PRIMARY KEY,
    game_date DATE,
    year INTEGER,
    month INTEGER,
    month_name VARCHAR,
    day INTEGER,
    day_of_the_week VARCHAR,
    quarter INTEGER,
    is_weekend BOOLEAN
);


CREATE TABLE IF NOT EXISTS chess_dw.dim_openings (
    pgn_eco_url VARCHAR PRIMARY KEY,
    opening_name VARCHAR(3),
    opening_family VARCHAR,
    eco_code VARCHAR
);


CREATE TABLE IF NOT EXISTS chess_dw.dim_users (
    user_id VARCHAR PRIMARY KEY,
    full_name VARCHAR,
    nationality VARCHAR
);
[2025-03-26T01:59:20.956+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_dw'
[2025-03-26T01:59:20.967+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_dw'
[2025-03-26T01:59:23.031+0000] {sql.py:509} INFO - Running statement: -- Fact Tables Creating
CREATE SCHEMA IF NOT EXISTS chess_dw;
CREATE TABLE IF NOT EXISTS chess_dw.fact_games (
    game_url VARCHAR PRIMARY KEY,
    time_control VARCHAR,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    game_duration_secs INTEGER,
    time_control VARCHAR,
    my_color VARCHAR,
    my_rating INTEGER,
    opponent_rating INTEGER,
    my_result VARCHAR,
    opponent_result VARCHAR,
    game_fen VARCHAR,
    opening_url VARCHAR,
    game_pgn VARCHAR
);


-- Dimension tables creation
CREATE TABLE IF NOT EXISTS chess_dw.dim_date (
    date_id INTEGER PRIMARY KEY,
    game_date DATE,
    year INTEGER,
    month INTEGER,
    month_name VARCHAR,
    day INTEGER,
    day_of_the_week VARCHAR,
    quarter INTEGER,
    is_weekend BOOLEAN
);


CREATE TABLE IF NOT EXISTS chess_dw.dim_openings (
    pgn_eco_url VARCHAR PRIMARY KEY,
    opening_name VARCHAR(3),
    opening_family VARCHAR,
    eco_code VARCHAR
);


CREATE TABLE IF NOT EXISTS chess_dw.dim_users (
    user_id VARCHAR PRIMARY KEY,
    full_name VARCHAR,
    nationality VARCHAR
);, parameters: None
[2025-03-26T01:59:23.452+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateColumn: column "time_control" specified more than once

[2025-03-26T01:59:23.515+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=load_data_warehouse, task_id=create_data_warehouse, run_id=manual__2025-03-12T14:13:58.419334+00:00, execution_date=20250312T141358, start_date=20250326T015920, end_date=20250326T015923
[2025-03-26T01:59:23.565+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-26T01:59:23.567+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 755 for task create_data_warehouse (column "time_control" specified more than once
; 29588)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateColumn: column "time_control" specified more than once

[2025-03-26T01:59:23.601+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T01:59:23.628+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-03-26T01:59:23.669+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T01:59:23.675+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
