[2025-03-23T16:45:38.535+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T16:45:38.563+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.load_dim_results scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-03-23T16:45:38.576+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.load_dim_results scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-03-23T16:45:38.576+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2025-03-23T16:45:38.597+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_dim_results> on 2025-02-01 00:00:00+00:00
[2025-03-23T16:45:38.612+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5050) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-23T16:45:38.615+0000] {standard_task_runner.py:72} INFO - Started process 5059 to run task
[2025-03-23T16:45:38.620+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'load_dim_results', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmp6395u3bu']
[2025-03-23T16:45:38.624+0000] {standard_task_runner.py:105} INFO - Job 668: Subtask load_dim_results
[2025-03-23T16:45:38.717+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.load_dim_results scheduled__2025-02-01T00:00:00+00:00 [running]> on host 8de4e0a4beb2
[2025-03-23T16:45:38.926+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='load_dim_results' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-03-23T16:45:38.927+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T16:45:38.946+0000] {logging_mixin.py:190} INFO - Received File Name: silver/fact-2025-02-games.parquet
[2025-03-23T16:45:39.021+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-23T16:45:39.036+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-23T16:45:40.474+0000] {logging_mixin.py:190} INFO - Successfully Loaded Dim Openings to Azure Storage as gold/dim_results.parquet
[2025-03-23T16:45:40.479+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T16:45:40.506+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T16:45:40.507+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=load_dim_results, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250323T164538, end_date=20250323T164540
[2025-03-23T16:45:40.565+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T16:45:40.605+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-23T16:45:40.610+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
