[2025-02-18T16:45:28.211+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:45:28.258+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-11-01T00:00:00+00:00 [queued]>
[2025-02-18T16:45:28.285+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-11-01T00:00:00+00:00 [queued]>
[2025-02-18T16:45:28.286+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:45:28.327+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2024-11-01 00:00:00+00:00
[2025-02-18T16:45:28.343+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3965) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:45:28.348+0000] {standard_task_runner.py:72} INFO - Started process 3966 to run task
[2025-02-18T16:45:28.352+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2024-11-01T00:00:00+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpwq5o9o0g']
[2025-02-18T16:45:28.355+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask extract_data_from_chess_api
[2025-02-18T16:45:28.486+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-11-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:45:28.716+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-01T00:00:00+00:00'
[2025-02-18T16:45:28.719+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:45:28.725+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2024 and Month: 11, formatted as 11
[2025-02-18T16:45:28.725+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2024/11
[2025-02-18T16:45:31.730+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 248
[2025-02-18T16:45:31.732+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-02-18T16:45:31.780+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:45:31.797+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:45:34.479+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as raw/2024-11-games.json
[2025-02-18T16:45:34.482+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-02-18T16:45:34.522+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:45:34.523+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2024-11-01T00:00:00+00:00, execution_date=20241101T000000, start_date=20250218T164528, end_date=20250218T164534
[2025-02-18T16:45:34.592+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:45:34.642+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:45:34.647+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-10T01:40:16.421+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T01:40:16.439+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-11-01T00:00:00+00:00 [queued]>
[2025-03-10T01:40:16.447+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-11-01T00:00:00+00:00 [queued]>
[2025-03-10T01:40:16.447+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-10T01:40:16.461+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2024-11-01 00:00:00+00:00
[2025-03-10T01:40:16.468+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=17624) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T01:40:16.469+0000] {standard_task_runner.py:72} INFO - Started process 17626 to run task
[2025-03-10T01:40:16.470+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2024-11-01T00:00:00+00:00', '--job-id', '553', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmp3qgpjbno']
[2025-03-10T01:40:16.472+0000] {standard_task_runner.py:105} INFO - Job 553: Subtask extract_data_from_chess_api
[2025-03-10T01:40:16.521+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-11-01T00:00:00+00:00 [running]> on host 70b3b9cfbba0
[2025-03-10T01:40:16.618+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-01T00:00:00+00:00'
[2025-03-10T01:40:16.620+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T01:40:16.622+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2024 and Month: 11, formatted as 11
[2025-03-10T01:40:16.622+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2024/11
[2025-03-10T01:40:18.052+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 248
[2025-03-10T01:40:18.053+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-03-10T01:40:18.077+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-10T01:40:18.089+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-10T01:40:19.903+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as bronze/2024-11-games.json
[2025-03-10T01:40:19.905+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-10T01:40:19.935+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T01:40:19.935+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2024-11-01T00:00:00+00:00, execution_date=20241101T000000, start_date=20250310T014016, end_date=20250310T014019
[2025-03-10T01:40:19.990+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T01:40:20.024+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T01:40:20.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
