[2025-02-18T16:41:37.699+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:41:37.731+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-02-18T16:41:37.748+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-02-18T16:41:37.749+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:41:37.776+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2024-01-01 00:00:00+00:00
[2025-02-18T16:41:37.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3783) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:41:37.791+0000] {standard_task_runner.py:72} INFO - Started process 3784 to run task
[2025-02-18T16:41:37.792+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmphyc6rsd0']
[2025-02-18T16:41:37.794+0000] {standard_task_runner.py:105} INFO - Job 215: Subtask extract_data_from_chess_api
[2025-02-18T16:41:37.883+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-01-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:41:38.035+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-02-18T16:41:38.037+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:41:38.043+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2024 and Month: 1, formatted as 01
[2025-02-18T16:41:38.043+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2024/01
[2025-02-18T16:41:39.962+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 514
[2025-02-18T16:41:39.962+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-02-18T16:41:40.062+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:41:40.083+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:41:43.003+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as raw/2024-01-games.json
[2025-02-18T16:41:43.004+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-02-18T16:41:43.043+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:41:43.044+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250218T164137, end_date=20250218T164143
[2025-02-18T16:41:43.093+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:41:43.137+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:41:43.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-10T01:36:35.652+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T01:36:35.668+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T01:36:35.676+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T01:36:35.676+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-10T01:36:35.690+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2024-01-01 00:00:00+00:00
[2025-03-10T01:36:35.697+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=17049) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T01:36:35.699+0000] {standard_task_runner.py:72} INFO - Started process 17051 to run task
[2025-03-10T01:36:35.699+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '523', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmpewnyo7js']
[2025-03-10T01:36:35.702+0000] {standard_task_runner.py:105} INFO - Job 523: Subtask extract_data_from_chess_api
[2025-03-10T01:36:35.750+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2024-01-01T00:00:00+00:00 [running]> on host 70b3b9cfbba0
[2025-03-10T01:36:35.849+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-10T01:36:35.850+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T01:36:35.852+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2024 and Month: 1, formatted as 01
[2025-03-10T01:36:35.853+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2024/01
[2025-03-10T01:36:37.884+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 514
[2025-03-10T01:36:37.885+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-03-10T01:36:37.947+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-10T01:36:37.968+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-10T01:36:39.910+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as bronze/2024-01-games.json
[2025-03-10T01:36:39.913+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-10T01:36:39.938+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T01:36:39.939+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250310T013635, end_date=20250310T013639
[2025-03-10T01:36:39.974+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T01:36:40.022+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T01:36:40.026+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
