[2025-02-18T16:08:00.704+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:08:00.734+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [queued]>
[2025-02-18T16:08:00.751+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [queued]>
[2025-02-18T16:08:00.751+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:08:00.774+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_json_to_fact_table> on 2023-02-01 00:00:00+00:00
[2025-02-18T16:08:00.784+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2796) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:08:00.787+0000] {standard_task_runner.py:72} INFO - Started process 2797 to run task
[2025-02-18T16:08:00.788+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'transform_json_to_fact_table', 'scheduled__2023-02-01T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpsnhei3d3']
[2025-02-18T16:08:00.790+0000] {standard_task_runner.py:105} INFO - Job 137: Subtask transform_json_to_fact_table
[2025-02-18T16:08:00.887+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:08:01.026+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='transform_json_to_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-01T00:00:00+00:00'
[2025-02-18T16:08:01.027+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:08:01.060+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:08:01.084+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:08:02.172+0000] {logging_mixin.py:190} INFO - /tmp/tmpry82i_17
[2025-02-18T16:08:02.178+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python_scripts.py", line 109, in transform_json_to_fact_table
    fact_table = duckdb.sql("""
                 ^^^^^^^^^^^^^^
duckdb.duckdb.BinderException: Binder Error: Referenced column "url" not found in FROM clause!
Candidate bindings: "json"
[2025-02-18T16:08:02.192+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pull_data_from_chess_api, task_id=transform_json_to_fact_table, run_id=scheduled__2023-02-01T00:00:00+00:00, execution_date=20230201T000000, start_date=20250218T160800, end_date=20250218T160802
[2025-02-18T16:08:02.219+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:08:02.220+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 137 for task transform_json_to_fact_table (Binder Error: Referenced column "url" not found in FROM clause!
Candidate bindings: "json"; 2797)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python_scripts.py", line 109, in transform_json_to_fact_table
    fact_table = duckdb.sql("""
                 ^^^^^^^^^^^^^^
duckdb.duckdb.BinderException: Binder Error: Referenced column "url" not found in FROM clause!
Candidate bindings: "json"
[2025-02-18T16:08:02.251+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T16:08:02.284+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:08:02.286+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T16:38:00.558+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:38:00.638+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [queued]>
[2025-02-18T16:38:00.675+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [queued]>
[2025-02-18T16:38:00.676+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-18T16:38:00.815+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_json_to_fact_table> on 2023-02-01 00:00:00+00:00
[2025-02-18T16:38:00.842+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3574) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T16:38:00.848+0000] {standard_task_runner.py:72} INFO - Started process 3575 to run task
[2025-02-18T16:38:00.851+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'transform_json_to_fact_table', 'scheduled__2023-02-01T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpucjqr127']
[2025-02-18T16:38:00.854+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask transform_json_to_fact_table
[2025-02-18T16:38:01.121+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [running]> on host 4ed02a11bf8e
[2025-02-18T16:38:01.525+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='transform_json_to_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-01T00:00:00+00:00'
[2025-02-18T16:38:01.533+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T16:38:01.608+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-02-18T16:38:01.645+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-02-18T16:38:02.725+0000] {logging_mixin.py:190} INFO - /tmp/tmpyx9gl6jk
[2025-02-18T16:38:04.727+0000] {logging_mixin.py:190} INFO - Successfully Transformed Data and Loaded to Azure Storage as silver/fact-2023-02-games.csv
[2025-02-18T16:38:04.731+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-18T16:38:04.788+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T16:38:04.791+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=transform_json_to_fact_table, run_id=scheduled__2023-02-01T00:00:00+00:00, execution_date=20230201T000000, start_date=20250218T163800, end_date=20250218T163804
[2025-02-18T16:38:04.901+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:38:04.990+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:38:05.001+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-10T01:33:09.750+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T01:33:09.791+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [queued]>
[2025-03-10T01:33:09.812+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [queued]>
[2025-03-10T01:33:09.813+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-10T01:33:09.845+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_json_to_fact_table> on 2023-02-01 00:00:00+00:00
[2025-03-10T01:33:09.881+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=16494) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T01:33:09.892+0000] {standard_task_runner.py:72} INFO - Started process 16496 to run task
[2025-03-10T01:33:09.891+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'transform_json_to_fact_table', 'scheduled__2023-02-01T00:00:00+00:00', '--job-id', '491', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmpnm6g_7gr']
[2025-03-10T01:33:09.901+0000] {standard_task_runner.py:105} INFO - Job 491: Subtask transform_json_to_fact_table
[2025-03-10T01:33:10.105+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.transform_json_to_fact_table scheduled__2023-02-01T00:00:00+00:00 [running]> on host 70b3b9cfbba0
[2025-03-10T01:33:10.351+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='transform_json_to_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-01T00:00:00+00:00'
[2025-03-10T01:33:10.354+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T01:33:10.435+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-10T01:33:10.459+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-10T01:33:11.265+0000] {logging_mixin.py:190} INFO - /tmp/tmptj2tv0az
[2025-03-10T01:33:11.285+0000] {logging_mixin.py:190} INFO - Previewing Dataframe
[2025-03-10T01:33:11.290+0000] {logging_mixin.py:190} INFO - game_url                        object
time_control                    object
rated                             bool
time_class                      object
rules                           object
white_rating                     int64
white_result                    object
black_rating                     int64
black_result                    object
pgn_event                       object
pgn_site                        object
game_date               datetime64[us]
pgn_white_user                  object
pgn_black_user                  object
pgn_result                      object
pgn_current_position            object
pgn_timezone                    object
pgn_eco                         object
pgn_eco_url                     object
start_time                      object
end_time                        object
end_game_date           datetime64[us]
pgn_raw                         object
pgn_trans                       object
dtype: object
[2025-03-10T01:33:11.314+0000] {logging_mixin.py:190} INFO - https://www.chess.com/game/live/69520095381	600	True	rapid	chess	701	timeout	814	win	Live Chess	Chess.com	2023-02-07 00:00:00	Rhythmbear1	percusanma	0-1	8/3q1p1p/Kp3k2/8/8/r7/8/8 w - -	UTC	C20	https://www.chess.com/openings/Kings-Pawn-Opening-Leonardis-Variation	14:45:05	14:59:00	2023-02-07 00:00:00	e4 e5 d3 Nc6 Nc3 Nd4 Nf3 Nxf3+ gxf3 Bb4 a3 Bxc3+ bxc3 d5 c4 dxc4 dxc4 Qxd1+ Kxd1 Be6 Rb1 O-O-O+ Ke1 b6 c5 Nf6 Ba6+ Kb8 cxb6 cxb6 a4 Bc8 Bd3 Rd7 Be3 Rhd8 a5 Rd6 f4 exf4 Bxf4 Kb7 a6+ Ka8 e5 Rxd3 exf6 Ra3 fxg7 Re8+ Kd2 Rg8 Rhg1 Bxa6 Rb3 Rxb3 cxb3 Bb5 h4 Kb7 h5 Kc8 Rc1+ Kd7 Rg1 Ke6 h6 Kf6 Bg5+ Kg6 Bf4+ Kf5 Rg5+ Kxf4 Rxb5 Kg4 Rb4+ Kg5 f4+ Kxh6 f5 Rxg7 f6 Rg2+ Kc3 Rg3+ Kd4 Rg4+ Ke5 Rxb4 Kd6 Rxb3 Ke7 Kg6 Kf8 Kxf6 Kg8 a5 Kf8 a4 Ke8 a3 Kd7 a2 Kd6 a1=Q Kc7 Qd1 Kb7 Qd7+ Ka6 Ra3+	1. e4 e5 2. d3 Nc6 3. Nc3 Nd4 4. Nf3 Nxf3+ 5. gxf3 Bb4 6. a3 Bxc3+ 7. bxc3 d5 8. c4 dxc4 9. dxc4 Qxd1+ 10. Kxd1 Be6 11. Rb1 O-O-O+ 12. Ke1 b6 13. c5 Nf6 14. Ba6+ Kb8 15. cxb6 cxb6 16. a4 Bc8 17. Bd3 Rd7 18. Be3 Rhd8 19. a5 Rd6 20. f4 exf4 21. Bxf4 Kb7 22. a6+ Ka8 23. e5 Rxd3 24. exf6 Ra3 25. fxg7 Re8+ 26. Kd2 Rg8 27. Rhg1 Bxa6 28. Rb3 Rxb3 29. cxb3 Bb5 30. h4 Kb7 31. h5 Kc8 32. Rc1+ Kd7 33. Rg1 Ke6 34. h6 Kf6 35. Bg5+ Kg6 36. Bf4+ Kf5 37. Rg5+ Kxf4 38. Rxb5 Kg4 39. Rb4+ Kg5 40. f4+ Kxh6 41. f5 Rxg7 42. f6 Rg2+ 43. Kc3 Rg3+ 44. Kd4 Rg4+ 45. Ke5 Rxb4 46. Kd6 Rxb3 47. Ke7 Kg6 48. Kf8 Kxf6 49. Kg8 a5 50. Kf8 a4 51. Ke8 a3 52. Kd7 a2 53. Kd6 a1=Q 54. Kc7 Qd1 55. Kb7 Qd7+ 56. Ka6 Ra3+
https://www.chess.com/game/live/69530046207	900+10	True	rapid	chess	728	checkmated	785	win	Live Chess	Chess.com	2023-02-07 00:00:00	tolusnt	Rhythmbear1	0-1	r1bk4/p4pB1/2pP4/1p6/1P6/1Bp2q1P/P1P1r3/3RK3 w - -	UTC	C47	https://www.chess.com/openings/Four-Knights-Game	17:27:53	17:59:36	2023-02-07 00:00:00	e4 e5 Nf3 Nf6 Nc3 Nc6 Bd3 d6 O-O Qd7 h3 g5 Nxg5 Rg8 Nxh7 Nxh7 Qe1 Nd4 b4 Nf3+ Kh1 Nxe1 Rxe1 Ng5 Re3 Rh8 Bb5 c6 Ba4 b5 Bb3 Bh6 d4 exd4 Re2 Nxh3 e5 Nxf2+ Kg1 Nh3+ Kf1 Qf5+ Ke1 Rg8 exd6+ Kd8 Bxh6 Re8 gxh3 dxc3 Rd1 Qf3 Bg7 Rxe2#	1. e4 e5 2. Nf3 Nf6 3. Nc3 Nc6 4. Bd3 d6 5. O-O Qd7 6. h3 g5 7. Nxg5 Rg8 8. Nxh7 Nxh7 9. Qe1 Nd4 10. b4 Nf3+ 11. Kh1 Nxe1 12. Rxe1 Ng5 13. Re3 Rh8 14. Bb5 c6 15. Ba4 b5 16. Bb3 Bh6 17. d4 exd4 18. Re2 Nxh3 19. e5 Nxf2+ 20. Kg1 Nh3+ 21. Kf1 Qf5+ 22. Ke1 Rg8 23. exd6+ Kd8 24. Bxh6 Re8 25. gxh3 dxc3 26. Rd1 Qf3 27. Bg7 Rxe2#
https://www.chess.com/game/live/70413320899	600	True	rapid	chess	680	abandoned	834	win	Live Chess	Chess.com	2023-02-17 00:00:00	Jxc_harvey14	Rhythmbear1	0-1	r3r3/5ppk/2p5/1pn2P2/p1n2BN1/8/PPP2KPP/4R3 w - -	UTC	D00	https://www.chess.com/openings/Queens-Pawn-Opening-1...d5-2.e3-Nf6	22:53:37	23:04:00	2023-02-17 00:00:00	e3 d5 d4 Nf6 Bb5+ c6 Ba4 a5 Nc3 b5 Bb3 a4 Bxd5 Nxd5 Ne4 Bf5 f3 e6 Nh3 Be7 O-O O-O Nef2 Bg6 e4 Nb6 f4 h6 Qg4 Bh7 f5 exf5 exf5 Bf6 Bxh6 Qxd4 Ng5 Qxg4 Nxg4 Bd4+ Rf2 Bxf2+ Kxf2 N8d7 Nxh7 Kxh7 Be3 Nc4 Bf4 Nc5 Re1 Rfe8	1. e3 d5 2. d4 Nf6 3. Bb5+ c6 4. Ba4 a5 5. Nc3 b5 6. Bb3 a4 7. Bxd5 Nxd5 8. Ne4 Bf5 9. f3 e6 10. Nh3 Be7 11. O-O O-O 12. Nef2 Bg6 13. e4 Nb6 14. f4 h6 15. Qg4 Bh7 16. f5 exf5 17. exf5 Bf6 18. Bxh6 Qxd4 19. Ng5 Qxg4 20. Nxg4 Bd4+ 21. Rf2 Bxf2+ 22. Kxf2 N8d7 23. Nxh7 Kxh7 24. Be3 Nc4 25. Bf4 Nc5 26. Re1 Rfe8
https://www.chess.com/game/live/71315651317	600	True	rapid	chess	886	win	801	abandoned	Live Chess	Chess.com	2023-02-28 00:00:00	Rhythmbear1	Doensen9078	1-0	4rk1r/Qp3p1p/3p1pb1/1B1R4/6P1/2P1P2P/PP6/5RK1 b - -	UTC	C50	https://www.chess.com/openings/Giuoco-Piano-Game-4.Nc3-d6	09:29:28	09:41:52	2023-02-28 00:00:00	e4 e5 Nf3 Nc6 Nc3 Bc5 Bc4 d6 d3 Bg4 h3 Bh5 g4 Bg6 Be3 Nd4 Nd5 Qf6 Nxf6+ gxf6 c3 Nxf3+ Qxf3 Bxe3 Qxe3 Rd8 d4 d5 exd5 e4 O-O Ne7 d6 cxd6 d5 Rc8 Bb5+ Kf8 Qxa7 e3 fxe3 Nxd5 Rad1 Re8 Rxd5	1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4 d6 5. d3 Bg4 6. h3 Bh5 7. g4 Bg6 8. Be3 Nd4 9. Nd5 Qf6 10. Nxf6+ gxf6 11. c3 Nxf3+ 12. Qxf3 Bxe3 13. Qxe3 Rd8 14. d4 d5 15. exd5 e4 16. O-O Ne7 17. d6 cxd6 18. d5 Rc8 19. Bb5+ Kf8 20. Qxa7 e3 21. fxe3 Nxd5 22. Rad1 Re8 23. Rxd5 
https://www.chess.com/game/live/71316868255	600	True	rapid	chess	934	win	880	abandoned	Live Chess	Chess.com	2023-02-28 00:00:00	Rhythmbear1	BjornABYT	1-0	r3k1nr/p4ppp/b1p5/3pp3/4q3/2B2N2/P4PPP/RN1Q2KR b kq -	UTC	C45	https://www.chess.com/openings/Scotch-Game	09:49:59	10:00:07	2023-02-28 00:00:00	e4 e5 Nf3 Nc6 d4 Bb4+ c3 Bd6 d5 Na5 b4 c6 bxa5 Qxa5 dxc6 bxc6 Bc4 Bb4 Bb2 d5 cxb4 Qxb4+ Bc3 Qxc4 Nfd2 Qd3 Nf3 Qxe4+ Kf1 Ba6+ Kg1	1. e4 e5 2. Nf3 Nc6 3. d4 Bb4+ 4. c3 Bd6 5. d5 Na5 6. b4 c6 7. bxa5 Qxa5 8. dxc6 bxc6 9. Bc4 Bb4 10. Bb2 d5 11. cxb4 Qxb4+ 12. Bc3 Qxc4 13. Nfd2 Qd3 14. Nf3 Qxe4+ 15. Kf1 Ba6+ 16. Kg1 
[2025-03-10T01:33:11.741+0000] {logging_mixin.py:190} INFO - Successfully Transformed Data and Loaded to Azure Storage as silver/fact-2023-02-games.parquet
[2025-03-10T01:33:11.741+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-10T01:33:11.759+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T01:33:11.760+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=transform_json_to_fact_table, run_id=scheduled__2023-02-01T00:00:00+00:00, execution_date=20230201T000000, start_date=20250310T013309, end_date=20250310T013311
[2025-03-10T01:33:11.828+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T01:33:11.879+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T01:33:11.883+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
