[2025-03-07T12:29:25.195+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-07T12:29:25.217+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-03-07T12:29:25.228+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-03-07T12:29:25.228+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-03-07T12:29:25.248+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2025-02-01 00:00:00+00:00
[2025-03-07T12:29:25.256+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8457) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-07T12:29:25.259+0000] {standard_task_runner.py:72} INFO - Started process 8458 to run task
[2025-03-07T12:29:25.260+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmptkbzlc6h']
[2025-03-07T12:29:25.262+0000] {standard_task_runner.py:105} INFO - Job 363: Subtask extract_data_from_chess_api
[2025-03-07T12:29:25.344+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2025-02-01T00:00:00+00:00 [running]> on host ebc50e07c8a4
[2025-03-07T12:29:25.471+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-03-07T12:29:25.472+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-07T12:29:25.476+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2025 and Month: 2, formatted as 02
[2025-03-07T12:29:25.477+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2025/02
[2025-03-07T12:29:27.199+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 247
[2025-03-07T12:29:27.200+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-03-07T12:29:27.253+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-07T12:29:27.274+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-07T12:29:29.977+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as bronze/2025-02-games.json
[2025-03-07T12:29:29.978+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-07T12:29:30.001+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-07T12:29:30.002+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250307T122925, end_date=20250307T122930
[2025-03-07T12:29:30.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-07T12:29:30.096+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-07T12:29:30.099+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-23T16:23:25.999+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T16:23:26.045+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-03-23T16:23:26.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-03-23T16:23:26.064+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-03-23T16:23:26.092+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_from_chess_api> on 2025-02-01 00:00:00+00:00
[2025-03-23T16:23:26.113+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4617) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-23T16:23:26.119+0000] {standard_task_runner.py:72} INFO - Started process 4633 to run task
[2025-03-23T16:23:26.119+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'extract_data_from_chess_api', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '661', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmpv7ohe1fd']
[2025-03-23T16:23:26.126+0000] {standard_task_runner.py:105} INFO - Job 661: Subtask extract_data_from_chess_api
[2025-03-23T16:23:26.231+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.extract_data_from_chess_api scheduled__2025-02-01T00:00:00+00:00 [running]> on host 8de4e0a4beb2
[2025-03-23T16:23:26.691+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='extract_data_from_chess_api' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-03-23T16:23:26.696+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T16:23:26.706+0000] {logging_mixin.py:190} INFO - Attempting to fetch data for Year: 2025 and Month: 2, formatted as 02
[2025-03-23T16:23:26.707+0000] {logging_mixin.py:190} INFO - Attemping to Fetch Data from: https://api.chess.com/pub/player/rhythmbear1/games/2025/02
[2025-03-23T16:23:29.420+0000] {logging_mixin.py:190} INFO - Successfully Fetched Data From CHess.com API, Records Pulled: 247
[2025-03-23T16:23:29.422+0000] {logging_mixin.py:190} INFO - Attempting to Upload Data to Azure Storage
[2025-03-23T16:23:29.537+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-23T16:23:29.604+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-23T16:23:34.007+0000] {logging_mixin.py:190} INFO - Successfully Uploaded Data to Azure Storage as bronze/2025-02-games.json
[2025-03-23T16:23:34.021+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-23T16:23:34.087+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T16:23:34.088+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=extract_data_from_chess_api, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250323T162326, end_date=20250323T162334
[2025-03-23T16:23:34.171+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T16:23:34.237+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-23T16:23:34.241+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
