[2025-03-31T17:52:49.997+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T17:52:50.288+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_data_from_chess_api.load_dim_time_control scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2025-03-31T17:52:50.472+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_data_from_chess_api.load_dim_time_control scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2025-03-31T17:52:50.528+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-31T17:52:50.997+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_dim_time_control> on 2023-11-01 00:00:00+00:00
[2025-03-31T17:52:51.098+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=12051) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-31T17:52:51.117+0000] {standard_task_runner.py:72} INFO - Started process 12095 to run task
[2025-03-31T17:52:51.157+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_data_from_chess_api', 'load_dim_time_control', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '995', '--raw', '--subdir', 'DAGS_FOLDER/collect_chess_data_dag.py', '--cfg-path', '/tmp/tmp7m66fuqi']
[2025-03-31T17:52:51.229+0000] {standard_task_runner.py:105} INFO - Job 995: Subtask load_dim_time_control
[2025-03-31T17:52:51.923+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_data_from_chess_api.load_dim_time_control scheduled__2023-11-01T00:00:00+00:00 [running]> on host 3b3ac09dc50a
[2025-03-31T17:52:52.795+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_data_from_chess_api' AIRFLOW_CTX_TASK_ID='load_dim_time_control' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2025-03-31T17:52:52.799+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T17:52:52.915+0000] {logging_mixin.py:190} INFO - Received File Name: silver/fact-2023-11-games.parquet
[2025-03-31T17:52:53.885+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 70, in deserialize_connection
    return Connection(conn_id=conn_id, uri=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 169, in __init__
    self._parse_from_uri(uri)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 257, in _parse_from_uri
    self.port = uri_parts.port
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'DefaultEndpointsProtocol=https;AccountName=rbchesssa;AccountKey=lG9W+utkpTNorE0rTLlfDMUZsTPleXk6pXv6NnfDTi'
[2025-03-31T17:52:54.120+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_storage'
[2025-03-31T17:53:10.104+0000] {logging_mixin.py:190} INFO - File To be loaded has (9, 2)
[2025-03-31T17:53:17.620+0000] {logging_mixin.py:190} INFO - Successfully Loaded to Azure Storage as gold/dim_time_control.parquet
[2025-03-31T17:53:17.739+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-31T17:53:17.904+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T17:53:17.914+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_data_from_chess_api, task_id=load_dim_time_control, run_id=scheduled__2023-11-01T00:00:00+00:00, execution_date=20231101T000000, start_date=20250331T175250, end_date=20250331T175317
[2025-03-31T17:53:18.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T17:53:18.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
